### ISSUE TITLE
Cannot build from source

### ISSUE THREAD

**Issue by andrefpoliveira** [HumanCompatibleAI/overcooked_ai#90]
Hey. I tried to follow the instructions to install the repo from source but I'm getting the following error (through pip everything worked fine):
```
Obtaining file:///C:/Users/Andre.LAPTOP01/overcooked_ai
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Andre.LAPTOP01\anaconda3\envs\overcooked_ai\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Andre.LAPTOP01\\overcooked_ai\\setup.py'"'"'; __file__='"'"'C:\\Users\\Andre.LAPTOP01\\overcooked_ai\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\ANDRE~1.LAP\AppData\Local\Temp\pip-pip-egg-info-5295cu1v'
         cwd: C:\Users\Andre.LAPTOP01\overcooked_ai\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Andre.LAPTOP01\overcooked_ai\setup.py", line 6, in <module>
        long_description = fh.read()
      File "C:\Users\Andre.LAPTOP01\anaconda3\envs\overcooked_ai\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 843: character maps to <undefined>
    ----------------------------------------
WARNING: Discarding file:///C:/Users/Andre.LAPTOP01/overcooked_ai. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by micahcarroll** [comment]
Thanks for reporting this! I'm guessing it might have to do with Windows installations. We'll be looking into this shortly.

As a note to self: in addition to solving the root cause of this bug, we should add a github actions test that tests installation on a windows computer.
